language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

python:
- 3.7
- 3.6

matrix:
  include:
  - os: linux
    python: 3.5
    install: pip install -e .[tests]
  - os: linux
    python: 3.7
    install: pip install -e .[tests,full,cov]
    script:
    - flake8
    - mypy .
    after_success:
    - pytest --cov
    - coveralls
  - os: osx
    language: minimal
    install: pip3 install -e .[tests]
# works but already tested on Appveyor
#  - os: windows
#    language: minimal
#    before_install:
#    - choco install python3
#    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"


install: pip install -e .[tests,full]

script: pytest -rsv

