language: python
fast_finish: true

python:
  - 3.6
  
os:
  - linux
  
group: travis_latest

env: FC=gfortran-6

git:
  depth: 3
  
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
      - octave


install: 
  - pip -q install -e .[tests,full]
  - cd bin
  - cmake ..
  - cmake --build .

script: 
  - ctest -V
  - cd ..
  
  - mypy . --ignore-missing-imports
  - flake8

after_success: 
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    pytest --cov;
    coveralls;
    fi

