language: python
fast_finish: true

python:
  - 2.7
  - "3.7-dev"
  
dist: xenial

os:
  - linux

git:
  depth: 3
  
  
addons:
  apt:
    packages:
      - octave


install: pip -q install -e .[tests]

script: coverage run tests/Test.py -v

after_success: 
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7* ]]; then coveralls; fi
