language: python
fast_finish: true

python:
  - 3.5

os:
  - linux

notifications:
  email: false

git:
  depth: 3


install: pip -q install -e .[tests]

script: coverage run tests/test.py -v

after_success: coveralls
