language: python
fast_finish: true

python:
  - 3.5
  - 3.6
  
os:
  - linux
  
group: travis_latest

env: FC=gfortran-6

git:
  depth: 3
  
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
      - octave


install: 
  - pip -q install -e .[tests,full]
  - cd bin
  - cmake ..
  - make

script: 
  - make test
  - mypy . --ignore-missing-imports
  - flake8

after_success: 
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    coverage run ../tests/test_all.py;
    coveralls;
    fi
    
after_failure:
  - ctest -V
