language: python
fast_finish: true

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - "3.7-dev"
  

os:
  - linux

git:
  depth: 3
  
  
addons:
  apt:
    packages:
      - octave


install: pip -q install -e .[tests]

script: 
  - coverage run tests/Test.py -v
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7* ]]; then
      cd tests;
      octave-cli -q Test.m;
      cd ..;
      
      cd bin;
      cmake ..
      make
      ./testmaptran
    fi

after_success: 
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7* ]]; then coveralls; fi
