language: python
python:
  - "3.4"
  - "2.7"
before_install: 
 sudo apt-get install -qq python-numpy python3-numpy
install: pip install  -q --allow-all-external  -r requirements.txt

script: coordconv3d.py
