language: python
fast_finish: true
sudo: false

python:
  - 2.7
  - "3.7-dev"

os:
  - linux

notifications:
  email: false

git:
  depth: 3


install: pip -q install -e .[tests]

script: coverage run tests/test.py -v

after_success: coveralls
