name: ci_stdlib_only

on:
  push:
    paths:
    - "**.py"
    - .github/workflows/ci_stdlib_only.yml
    - "!scripts/"
    pull-request:
    - "**.py"
    - .github/workflows/ci_stdlib_only.yml

jobs:

  stdlib_only:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} Python ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10']
        os: [ 'ubuntu-latest']
        include:
        - os: macos-latest
          python-version: '3.10'
        - os: windows-latest
          python-version: '3.10'

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install .[tests]

    - run: pytest
